- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - ansible
      - mas
      # basics
      - bat
      - exa
      - gawk
      - jq
      - peco
      - starship
      - colordiff
      - tokei
      # - gum
      # - httpie
      - procs
      # Taskfile
      - go-task
      # rust
      - rustup
      - rust-analyzer
      # aws
      - aws-cdk
      - awscli
      # node
      - node@18
      - node@20
      - yarn
      # python
      - poetry
      - python@3.9
      - python@3.10
      - python@3.11
      - python@3.12
      # after install, you must type: brew link certifi
      - certifi
      ## for scipy
      - lapack
      ## for matplotlib
      - libjpeg
      ## for psycopg2
      # - postgresql
      ## for numpy, see: https://github.com/numpy/numpy/issues/17807
      - openblas
      ## for lightgbm
      - libomp
      # - cmake
      ## for mecab
      - mecab
      - mecab-ipadic
      ## for tables(library)
      - hdf5
      - c-blosc
      # yubikey
      - ykman
      # sshpass
      - hudochenkov/sshpass/sshpass
      # for ssh2-python
      - openssl@3
      # for SSL
      - mkcert
      # portscan
      - nmap
      # simple-hotkeys-daemon
      - koekeishiya/formulae/skhd
      - yabai
      # neovim
      - neovim
      - neovim-qt
