- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - sheldon
      - ansible
      - mas
      # basics
      - bat
      - eza
      - gawk
      - jq
      - fzf
      - starship
      - colordiff
      - tokei
      - direnv
      - procs
      # Taskfile
      - go-task
      # rust
      - rustup
      - rust-analyzer
      # aws
      - aws-cdk
      - awscli
      # node
      # - node@20
      # - node
      - yarn
      # python
      - rye
      - uv
      - python@3.10
      - python@3.11
      - python@3.12
      # after install, you must type: brew link certifi
      - certifi
      ## for scipy
      - lapack
      ## for matplotlib
      - libjpeg
      ## for psycopg2
      # - postgresql
      - mysql
      - tbls
      ## for numpy, see: https://github.com/numpy/numpy/issues/17807
      - openblas
      ## for lightgbm
      - libomp
      # - cmake
      ## for mecab
      - mecab
      - mecab-ipadic
      ## for tables(library)
      - hdf5
      - c-blosc
      # yubikey
      - ykman
      # sshpass
      - hudochenkov/sshpass/sshpass
      # for ssh2-python
      - openssl@3
      # for SSL
      - mkcert
      # portscan
      - nmap
      # simple-hotkeys-daemon
      - koekeishiya/formulae/skhd
      - yabai
      # neovim
      - neovim
      - ripgrep
      - vhs
      - im-select
      - gh
      - ghq
      # font
      - font-hack-nerd-font
      # $ img2sixel to show image in terminal
      - libsixel
      # Git
      - jesseduffield/lazygit/lazygit
      - git-flow
      # Docker
      - lazydocker
      # document a Database
      # see: https://github.com/k1LoW/tbls
      - k1LoW/tap/tbls
      # benchmark
      # - wrk2 

