- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - ansible
      - mas
      # basics
      - bat
      - exa
      - gawk
      - jq
      - peco
      - starship
      - colordiff
      - tokei
      - gum
      - httpie
      - procs
      # rust
      - rustup
      - rust-analyzer
      # aws
      - aws-cdk
      - awscli
      # node
      - node@16
      # python
      - poetry
      ## for scipy
      - lapack
      ## for matplotlib
      - libjpeg
      ## for psycopg2
      - postgresql
      ## for numpy, see: https://github.com/numpy/numpy/issues/17807
      - openblas
      ## for lightgbm
      - libomp
      - cmake
      ## for mecab
      - mecab
      - mecab-ipadic
      # yubikey
      - ykman
