version: '3'

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true

  dotfile:
    desc: create symbolic link
    cmds:
      - sh ./bin/dotfile_symbolic_link.sh

  ansible:
    desc: run-ansible
    dir: ./ansible
    preconditions:
      - test -f playbook.yml
      - test -f requirements.yml
    cmds:
      - ansible-playbook playbook.yml
