version: '3'

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true
  
  nix:
    desc: update nix and format nix-files
    dir: ./nix
    cmds:
      - nix run .#update
      - nix store gc

  github:
    desc: add gh-plugins
    cmds:
      - gh extension install dlvhdr/gh-dash
      
  update-github-pat:
    desc: update token; e.g. $ token={} task update-github-pat
    cmds:
      - sh ./bin/update_github_pat.sh {{.token}}
    requires:
      vars: [token]

  start:
    desc: start services
    cmds:
      - brew services start sketchybar
      - aerospace reload-config
