version: '3'

includes:
  dotfile: ./taskfile.dotfile.yml

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true

  ansible:
    desc: run-ansible
    dir: ./ansible
    preconditions:
      - test -f playbook.yml
      - test -f requirements.yml
    cmds:
      - task: tap
      - ansible-playbook playbook.yml

  tap:
    desc: add external-repositories
    internal: true
    cmds:
      - brew tap koekeishiya/formulae
      - brew tap k1low/tap
      - brew tap jesseduffield/lazygit
      - brew tap jesseduffield/lazydocker
      - brew tap daipeihust/tap
      - brew tap FelixKratz/formulae
      - brew tap localstack/tap 
      - brew tap FelixKratz/formulae
      - brew tap hashicorp/tap

  github:
    desc: add gh-plugins
    cmds:
      - gh extension install dlvhdr/gh-dash
      
  update-github-pat:
    desc: update token; e.g. $ token={} task update-github-pat
    cmds:
      - sh ./bin/update_github_pat.sh {{.token}}
    requires:
      vars: [token]

  start:
    desc: start services
    cmds:
      - brew services start sketchybar
      - aerospace reload-config
