version: '3'

includes:
  dotfile: ./taskfile.dotfile.yml

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true
  
  ansible:
    desc: run-ansible
    dir: ./ansible
    preconditions:
      - test -f playbook.yml
      - test -f requirements.yml
    cmds:
      - ansible-playbook playbook.yml

  github:
    desc: add gh-plugins
    cmds:
      - gh extension install dlvhdr/gh-dash
      
  update-github-pat:
    desc: update token; e.g. $ token={} task update-github-pat
    cmds:
      - sh ./bin/update_github_pat.sh {{.token}}
    requires:
      vars: [token]

  start:
    desc: start services
    cmds:
      - brew services start sketchybar
      - aerospace reload-config
