- name: install applications from app store
  community.general.mas:
    upgrade_all: yes
    id:
      # LINE
      - 539883307
      # Slack
      - 803453959
      # Claude desktop
      - 6473753684
