services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama

  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.26
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./openhands-state:/.openhands-state
      - ./data:/workspace
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.26-nikolaik
      - LOG_ALL_EVENTS=true
      - WORKSPACE_MOUNT_PATH=./openhands/data
# volumes:
#   ollama:

