customCommands:
  - key: '<c-n>'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'git-flow'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: feature
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
      - type: 'input'
        input: 'branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git flow {{.Form.BranchType}} start {{.Form.BranchName}}"
    loadingText: 'Creating Branch'
  - key: '<c-c>'
    context: 'files'
    prompts:
      - type: 'menu'
        title: 'git-commit-prefix'
        key: 'Prefix'
        options:
          - name: 'fix'
            description: 'bug fix.'
            value: 'fix'
          - name: 'feat'
            description: 'add new feature'
            value: 'feat'
          - name: 'refactor'
            description: 'refactor codes'
            value: 'refactor'
          - name: 'docs'
            description: 'update documents.'
            value: 'docs'
          - name: 'style'
            description: 'format, lint.'
            value: 'style'
          - name: 'test'
            description: 'add test.'
            value: 'test'
          - name: 'chore'
            description: 'others.'
            value: 'chore'
      - type: 'input'
        input: 'commit message'
        key: 'CommitMessage'
        initialValue: ''
    command: "git commit -m '{{.Form.Prefix}}: {{.Form.CommitMessage}}'"
    loadingText: 'Creating Branch'
