- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - aws-vault
      - notion
      - iterm2
      - google-chrome
      - fork
      - jetbrains-toolbox
      - visual-studio-code
