#!/bin/sh

### Color Tokens
export RED=0xfff38ba8
export YELLOW=0xfff9e2af
export ORANGE=0xfffab387
export BLUE_BG=0x7f1e1e2e
export GREEN=0xffb8e986
export GREEN_BG=0x19a6e3a1
export LAVENDER=0xffb4befe
export LAVENDER_BG=0x19b4befe
export FLAMINGO=0xfff2cdcd
export FLAMINGO_BG=0x19f2cdcd
export PINK=0xfff5c2e7
export PINK_BG=0x19f5c2e7
export OVERLAY1=0xff7f849c
export DARK=0xa024273a
export DARK_PLUS=0xe024273a
export TRANSPARENT=0x70000000

# General Bar colors
export BAR_BG_COLOR=$DARK
export BAR_BOARDER_COLOR=$DARK_PLUS

# General Item colors
export LABEL_COLOR=$OVERLAY1

export POPUP_BACKGROUND_COLOR=0xFF272936

# Item colors
export SPACE_SELECTED=$LAVENDER
export SPACE_SELECTED_BACKGROUND=$LAVENDER_BG
export SPACE=$OVERLAY1
export SPACE_BACKGROUND=0x00000000

export CALENDAR=$LAVENDER
export CALENDAR_BACKGROUND=$LAVENDER_BG

export BATTERY=$GREEN
export BATTERY_WARNING=$YELLOW
export BATTERY_CRITICAL=$RED
export BATTERY_BACKGROUND=$GREEN_BG

export WIFI=$FLAMINGO
export WIFI_BACKGROUND=$FLAMINGO_BG

export VOLUME=$PINK
export VOLUME_BACKGROUND=$PINK_BG
